### ISSUE TITLE
How to fix audio

### ISSUE THREAD

**Issue by Itsuwarii** [danielhk/android_device_lenovo_aio_otfp#4]
@danielhk  I have encountered some problems when making a third-party rom for VIVO Y67(MT6750).

Audio does not work, I try to replace the inventory rom libaudiocompensationfilter.so libaudiocomponentengine.so libaudiocustparam.so libaudiodcrflt.so system/etc/audio_param and system/etc audio configuration for inventory, but the external still can not work, but Bluetooth is normal.

This is log: https://github.com/VIVOY67-Dev/android_device_vivo_y67/wiki
Device tree: https://github.com/VIVOY67-Dev/android_device_vivo_y67

Can you help me, thanks first :)

**Comment by BabQ** [comment]
> @danielhk I have encountered some problems when making a third-party rom for VIVO Y67(MT6750).
> 
> Audio does not work, I try to replace the inventory rom libaudiocompensationfilter.so libaudiocomponentengine.so libaudiocustparam.so libaudiodcrflt.so system/etc/audio_param and system/etc audio configuration for inventory, but the external still can not work, but Bluetooth is normal.
> 
> This is log: https://github.com/VIVOY67-Dev/android_device_vivo_y67/wiki
> Device tree: https://github.com/VIVOY67-Dev/android_device_vivo_y67
> 
> Can you help me, thanks first :)
